@baseUrl=http://localhost:8000/api/v1/auth

### register
POST {{baseUrl}}/register
Content-Type: application/json

{
  "username": "john",
  "email": "john@apple.seed",
  "password": "12345678"
}

### login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "john@apple.seed",
  "password": "12345678"
}